import streamlit as st
import json
import random
import os
import pandas as pd
from datetime import datetime
import time
import streamlit.components.v1 as components
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# --- 1. DIZIONARIO TRADUZIONI ---
# Qui definiamo tutte le parole che cambiano
T = {
    "warning_note": {
        "it": "⚠️ **NOTA IMPORTANTE**: I testi sono originariamente in inglese, pertanto alcune traduzioni potrebbero non risultare perfettamente naturali in italiano. Se possiedi una buona conoscenza della lingua inglese, è consigliato leggere il testo nella sua lingua originale.",
        "en": ""
    },
    "consent_title": {
        "it": "📝 Informativa e Consenso di Partecipazione alla Ricerca",
        "en": "📝 Informed Consent for Research Participation"
    },
    "consent_text": {
    "it": """
    **Ti invitiamo a leggere attentamente quanto segue prima di proseguire.**
    
    **Scopo della ricerca:** Lo studio si propone di analizzare la correlazione tra la valutazione umana di testi creativi (scritti sia da esseri umani che da LLM) e la valutazione automatica effettuata tramite approccio LLM-as-a-judge (l'uso di LLM per giudicare testi basandosi su criteri predefiniti). L'obiettivo finale è verificare il grado di allineamento tra le metriche di giudizio umane e quelle generate dai modelli linguistici.
    
    **Procedura di raccolta:** La raccolta dati avverrà tramite un'applicazione web dedicata. Ai partecipanti verrà richiesto di:
    1. Fornire alcune informazioni demografiche di base (età, genere, titolo di studio) e indicare il proprio livello di esperienza con gli LLM.
    2. Leggere un breve testo e valutarne le caratteristiche utilizzando una scala Likert che va da 1 a 5. (circa 5-10 minuti tra lettura e valutazione).
    3. Al termine, scegliere se concludere la sessione o procedere con la valutazione di un nuovo testo, fino a esaurimento del campione.
    
    **Anonimato e Open Science:** Tutti i dati raccolti saranno **rigorosamente anonimi** e non riconducibili all'identità dei partecipanti (non verranno raccolti indirizzi IP, nomi o altri dati identificativi). I dati verranno salvati su foglio di calcolo in cloud (Google Sheets) con accesso riservato. In ottica di "Open Science", i dati anonimizzati verranno conservati a tempo indeterminato e verranno resi **pubblicamente disponibili** alla comunità scientifica come dataset per future ricerche nel campo dell'Natural Language Processing (NLP).
    
    **Volontarietà e Recesso:** La partecipazione è strettamente volontaria. Puoi interrompere la sessione in qualsiasi momento chiudendo il browser senza alcuna conseguenza. Tuttavia, data la natura totalmente anonima dei dati, una volta inviato il questionario **non sarà possibile richiederne la cancellazione**, in quanto non saremo in grado di associare le risposte alla tua identità.
    
    **Contatti:** Per domande o dubbi riguardanti questo studio, puoi contattare il responsabile della ricerca all'indirizzo: alessandro.tutone@studio.unibo.it.
    
    Cliccando su **"_Accetto e Partecipo_"**, dichiari di aver letto queste informazioni, di essere maggiorenne e di acconsentire volontariamente all'uso e alla eventuale pubblicazione dei dati in forma anonima.
    """,
    "en": """
    **Please read the following information carefully before proceeding.**
    
    **Research Purpose:** This study aims to analyze the correlation between human evaluation of creative texts (written by both humans and LLMs) and automatic evaluation performed using the *LLM-as-a-judge* approach (using LLMs to judge texts based on predefined criteria). The ultimate goal is to verify the degree of alignment between human judgment metrics and those generated by language models.
    
    **Data Collection Procedure:** Data collection will take place via a dedicated web application. Participants will be asked to:
    1. Provide some basic demographic information (age, gender, education level) and indicate their level of experience with LLMs.
    2. Read a short text and evaluate its features using a Likert scale from 1 to 5 (estimated time: 5-10 minutes for reading and evaluation).
    3. Upon completion, choose whether to end the session or repeat the procedure with additional texts, until the available sample is exhausted.
    
    **Anonymity and Open Science:** All collected data will be **strictly anonymous** and cannot be traced back to the participants' identity (IP addresses, names, or other identifiers will not be collected). Data will be stored on a cloud spreadsheet (Google Sheets) with restricted access.
    In the spirit of "Open Science," anonymized data will be retained indefinitely and made **publicly available** to the scientific community as a dataset for future research in the field of Natural Language Processing (NLP).
    
    **Voluntary Participation and Withdrawal:** Participation is strictly voluntary. You may discontinue the session at any time by closing your browser without any consequences. However, given the totally anonymous nature of the data, once the questionnaire is submitted, **it will not be possible to request its deletion**, as we will be unable to associate the responses with your identity.
    
    **Contact:** For questions or concerns regarding this study, you may contact the research lead at: alessandro.tutone@studio.unibo.it.
    
    By clicking **"_I Agree and Participate_"**, you declare that you have read this information, are of legal age, and voluntarily consent to the use and potential publication of the data in an anonymous form.
    """
    },
    "agree_btn": {"it": "✅ Accetto e Partecipo", "en": "✅ I Agree and Participate"},
    "decline_btn": {"it": "❌ Non Accetto", "en": "❌ I Decline"},
    "decline_msg": {"it": "Hai deciso di non partecipare. Puoi chiudere questa scheda.", "en": "You decided not to participate. You may close this tab."},
    "title_demo": {
        "it": "📋 Studio sulla Creatività Testuale",
        "en": "📋 Study about Text Creativity"
    },
    "intro_demo": {
        "it": """**Benvenuto**! Ti sarà richiesto di leggere un breve testo (~5-10 min) e poi di valutarne alcune caratteristiche.
        Una volta completato, potrai passare al testo successivo oppure terminare la tua valutazione.
        Tutti i testi sono disponibili sia in italiano che in inglese, a seconda della tua scelta. Le tue risposte saranno salvate in modo anonimo per scopi di ricerca.\n\nPrima di iniziare, inserisci alcune informazioni statistiche.""",
        "en": """**Welcome**! You will be asked to read a short text (~5-10 min) and then rate some of its features.
        Once completed, you can move to the next text or finish your session.
        All texts are available both in Italian an in English, depending on your choice. Your answers will be saved anonymously for research purposes.\n\n**IMPORTANT NOTE**: All texts were originally written in English. Therefore, the Italian versions might be less accurate/natural. 
        If you are fluent in English, we recommend to keep selected the English version.\n\nBefore starting, please provide some demographic information."""
    },
    "age": {"it": "Età", "en": "Age"},
    "gender": {"it": "Genere", "en": "Gender"},
    "gender_opts": {
        "it": ["Uomo", "Donna", "Non binario", "Altro", "Preferisco non dire"],
        "en": ["Male", "Female", "Non-binary", "Other", "Prefer not to say"]
    },
    "edu": {"it": "Titolo di Studio", "en": "Education Level"},
    "edu_opts": {
        "it": ["Licenza Media", "Diploma", "Laurea Triennale", "Laurea Magistrale", "Dottorato", "Altro"],
        "en": ["High School", "Bachelor's Degree", "Master's Degree", "PhD", "Other"]
    },
    "exp": {"it": "Esperienza con LLMs (_ChatGPT_, _Gemini_, _Claude_, ...). Quanto spesso li usi?", "en": "Experience with LLMs(_ChatGPT_, _Gemini_, _Claude_, ...). How often do you use them?"},
    "exp_opts": {
        "it": ["Mai usati", "Provati per curiosità", "Qualche volta", "Spesso","Se non tutti i giorni, quasi"],
        "en": ["Never used", "Tried out of curiosity", "Occasionally", "Often", "If not daily, almost"]
    },
    "start_btn": {"it": "Inizia a Valutare", "en": "Start Evaluating"},
    "eval_title": {"it": "Valutazione", "en": "Evaluation"},
    "text_id_label": {"it": "ID Testo", "en": "Text ID"},
    "seen_label": {"it": "Visti", "en": "Seen"},
    "instructions": {
        "it": "Valuta il testo sopra secondo i seguenti criteri (1 = Minimo, 5 = Massimo):",
        "en": "Rate the text above according to the following criteria (1 = Lowest, 5 = Highest):"
    },
    "q1": {"it": "**SORPRESA**\n\n_La capacità del testo di stupire il lettore. Il contenuto prende una direzione inaspettata, introduce un colpo di scena o rompe le aspettative comuni rispetto all'argomento trattato?_", "en": "**SURPRISE**\n\n_The text's ability to astonish the reader. Does the content take an unexpected turn, introduce a plot twist, or break common expectations regarding the topic discussed?_"},
    "q2": {"it": "**NOVITÀ**\n\n_Il grado di innovazione del concetto. L'idea alla base del testo è fresca e nuova, oppure è una rielaborazione di concetti già noti e abusati?_", "en": "**NOVELTY**\n\n_The degree of innovation of the concept. Is the idea behind the text fresh and new, or is it a rehash of well-known and overused concepts?_"},
    "q3": {"it": "**VALORE**\n\n_Il merito intrinseco del testo. La lettura è stata arricchente, interessante o emotivamente coinvolgente? Il testo ha un 'peso' o una qualità letteraria percepibile?_", "en": "**VALUE**\n\n_The intrinsic merit of the text. Was the reading enriching, interesting, or emotionally engaging? Does the text have a perceivable 'weight' or literary quality?_"},
    "q4": {"it": "**AUTENTICITÀ**\n\n_La percezione di una voce genuina e personale. Il testo sembra scritto con uno stile proprio e sentito, oppure appare meccanico, artificiale o copiato?_", "en": "**AUTHENTICITY**\n\n_The perception of a genuine and personal voice. Does the text seem written with its own heartfelt style, or does it appear mechanical, artificial, or copied?_"},
    "q5": {"it": "**ORIGINALITÀ**\n\n_La rarità statistica dell'approccio. Rispetto ad altri testi sullo stesso tema, quanto è unico questo approccio? Evita i cliché e i luoghi comuni?_", "en": "**ORIGINALITY**\n\n_The statistical rarity of the approach. Compared to other texts on the same topic, how unique is this approach? Does it avoid clichés and commonplaces?_"},
    "q6": {"it": "**EFFICACIA**\n\n_La capacità del testo di raggiungere il suo obiettivo. Se è una storia, intrattiene? Se è una risposta, soddisfa la richiesta (prompt) in modo completo e convincente?_", "en": "**EFFECTIVENESS**\n\n_The text's ability to achieve its goal. If it's a story, does it entertain? If it's a response, does it satisfy the request (prompt) in a complete and convincing manner?_"},
    "q7": {"it": "**FLUIDITÀ**\n\n_La scorrevolezza linguistica e la facilità di generazione delle idee. Il testo si legge bene, senza intoppi grammaticali o logici? Le idee fluiscono naturalmente l'una nell'altra?_", "en": "**FLUENCY**\n\n_Linguistic smoothness and ease of idea generation. Does the text read well, without grammatical or logical hiccups? Do the ideas flow naturally from one to another?_"},
    "q8": {"it": "**FLESSIBILITÀ**\n\n_La varietà di prospettive o temi toccati. Il testo riesce a collegare concetti diversi, cambiare punto di vista o adattarsi a vincoli narrativi in modo agile?_", "en": "**FLEXIBILITY**\n\n_The variety of perspectives or themes touched upon. Does the text manage to connect different concepts, change viewpoints, or adapt to narrative constraints in an agile manner?_"},
    "q9": {"it": "**ELABORAZIONE**\n\n_La ricchezza di dettagli e la profondità di sviluppo. Il testo espande l'idea principale con descrizioni vivide, sfumature e complessità, o rimane superficiale e scarno?_", "en": "**ELABORATION**\n\n_The richness of details and depth of development. Does the text expand the main idea with vivid descriptions, nuances, and complexity, or does it remain superficial and sparse?_"},
    "q10": {"it": "**UTILITÀ**\n\n_La pertinenza e l'applicabilità rispetto al contesto. Il testo è coerente con la richiesta iniziale? È 'utile' nel senso che funziona come risposta valida e sensata al prompt?_", "en": "**UTILITY**\n\n_The relevance and applicability to the context. Is the text consistent with the initial request? Is it 'useful' in the sense that it functions as a valid and sensible response to the prompt?_"},
    "q11": {"it": "**CREATIVITÀ**\n\n_Il giudizio complessivo sull'ingegno e l'immaginazione del testo. L'autore è riuscito a combinare idee in modo unico, andando oltre l'ovvio per creare qualcosa che colpisce sia per la sua inventiva che per la sua esecuzione? È il 'fattore wow' che distingue un testo banale da uno ispirato._", "en": "**CREATIVITY**\n\n_The overall judgment on the text's ingenuity and imagination. Has the author managed to combine ideas in a unique way, going beyond the obvious to create something that impresses both for its inventiveness and execution? Is it the 'wow factor' that distinguishes a mundane text from an inspired one._"},

    "submit_btn": {"it": "Invia Valutazione", "en": "Submit Evaluation"},
    "success_msg": {"it": "✅ Valutazione salvata! Caricamento prossimo testo...", "en": "✅ Saved! Loading next text..."},
    "finish_msg": {"it": "🎉 Hai valutato TUTTI i testi disponibili! Grazie.", "en": "🎉 You evaluated ALL available texts! Thank you."},
    "exit_btn": {"it": "Termina Sessione (Esci)", "en": "End Session (Exit)"},
    "thank_you": {"it": "❤️Grazie per il tuo contributo!", "en": "❤️Thank you for your contribution!"},
    "final_message": {
        "it": "Grazie per aver dedicato il tuo tempo a questo studio. Un ampio campione di valutazioni è cruciale per garantire la significatività statistica dei dati raccolti.\n\nIl tuo contributo è fondamentale per comprendere le differenze di percezione tra lettori umani e sistemi automatici. Gli stessi testi, infatti, verranno sottoposti a valutazione da parte di diversi Large Language Models (LLM) utilizzando le medesime metriche.\n\nSe desideri supportare ulteriormente questa ricerca, ti invitiamo a condividere il link (https://creativity-evaluation.streamlit.app/) con altre persone potenzialmente interessate. Ogni contributo aggiuntivo migliora la qualità dei risultati.\n\nGrazie ancora per la collaborazione. Puoi ora chiudere questa finestra.",
        
        "en": "Thank you for dedicating your time to this study. A broad sample of evaluations is crucial to ensure the statistical significance of the collected data.\n\nYour contribution is essential for understanding the differences in perception between human readers and automated systems. These texts will subsequently be evaluated by various Large Language Models (LLMs) using the same metrics.\n\nIf you wish to further support this research, we invite you to share this link (https://creativity-evaluation.streamlit.app/) with others who might be interested. Every additional contribution improves the quality of our results.\n\nThank you again for your collaboration. You may now close this window."
    },
    "error_save": {"it": "Errore nel salvataggio", "en": "Error saving data"}
}

# --- FUNZIONI DI UTILITÀ ---
def scroll_to_top():
    js = """
    <script>
        // Ritardo di 100ms per dare tempo al rendering mobile di assestarsi
        setTimeout(function() {
            var targets = [
                // Tenta di scrollare la finestra principale
                window.parent.document.documentElement,
                window.parent.document.body,
                // Tenta di scrollare i contenitori specifici di Streamlit
                window.parent.document.querySelector('[data-testid="stAppViewContainer"]'),
                window.parent.document.querySelector('[data-testid="stMain"]'),
                window.parent.document.querySelector(".main")
            ];

            targets.forEach(function(target) {
                if (target) {
                    target.scrollTop = 0;
                    // Metodo alternativo per browser moderni
                    target.scroll({
                        top: 0,
                        left: 0,
                        behavior: 'auto' // 'auto' è scatto immediato, 'smooth' è animato
                    });
                }
            });
            
            // Tentativo finale globale
            window.parent.scrollTo(0, 0);
        }, 150);
    </script>
    """
    components.html(js, height=0)

def get_google_sheet():
    scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']
    creds_dict = st.secrets["gcp_service_account"]
    creds = ServiceAccountCredentials.from_json_keyfile_dict(creds_dict, scope)
    client = gspread.authorize(creds)
    # Assicurati che il nome sia corretto
    return client.open("texts_evaluation_sheet").sheet1 

@st.cache_data
def load_texts():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    json_path = os.path.join(base_dir, "dataset_full_200.json")
    with open(json_path, 'r') as f:
        data = json.load(f)
    return data

data_texts = load_texts()

# --- BLOCCO USCITA ---
if 'finito' in st.session_state and st.session_state['finito']:
    lang = st.session_state.get('language_choice', 'it') # Recupera lingua per saluto
    scroll_to_top()
    st.title(T['thank_you'][lang])
    st.write(T['final_message'][lang])
    st.balloons()
    st.stop()

# --- SELETTORE LINGUA (Sidebar o Top) ---
# Lo mettiamo nella sidebar o in alto. Qui lo metto in alto a destra usando le colonne.
col_logo, col_lang = st.columns([8, 2])
with col_lang:
    # Salviamo la scelta nello stato
    lang_code = st.radio("Language / Lingua", ["🇮🇹 Italiano", "🇬🇧 English"], index=1)
    
    # Convertiamo la scelta in 'it' o 'en' per usare il dizionario
    curr_lang = 'it' if "Italiano" in lang_code else 'en'
    st.session_state['language_choice'] = curr_lang

# --- INIZIALIZZAZIONE STATO ---
if 'user_info' not in st.session_state:
    st.session_state['user_info'] = None
if 'current_text' not in st.session_state:
    st.session_state['current_text'] = None
if 'seen_ids' not in st.session_state:
    st.session_state['seen_ids'] = []
if 'consent_given' not in st.session_state:
    st.session_state['consent_given'] = False

# ==========================================
# FASE 0: CONSENSO INFORMATO
# ==========================================
if not st.session_state['consent_given']:
    st.info("ℹ️ **NOTA IMPORTANTE**: Questa è un'informazione utile per l'utente.")
    st.title(T['consent_title'][curr_lang])
    
    # Box stile "documento"
    with st.container(border=True):
        st.markdown(T['consent_text'][curr_lang])
    
    col_c1, col_c2 = st.columns([1, 1])
    
    with col_c1:
        if st.button(T['agree_btn'][curr_lang], use_container_width=True, type="primary"):
            st.session_state['consent_given'] = True
            st.session_state['force_scroll'] = True # Per scrollare in alto nella prossima pagina
            st.rerun()
            
    with col_c2:
        if st.button(T['decline_btn'][curr_lang], use_container_width=True):
            st.warning(T['decline_msg'][curr_lang])
            st.stop()

# ==========================================
# FASE 1: DATI DEMOGRAFICI
# ==========================================
elif st.session_state['user_info'] is None:
    if T['warning_note'][curr_lang]:
        st.error(T['warning_note'][curr_lang])
    st.title(T['title_demo'][curr_lang])
    st.write(T['intro_demo'][curr_lang])
    
    with st.form("demographics"):
        age = st.number_input(T['age'][curr_lang], min_value=18, max_value=99, step=1)
        
        # Le opzioni cambiano in base alla lingua
        gender = st.selectbox(T['gender'][curr_lang], T['gender_opts'][curr_lang])
        education = st.selectbox(T['edu'][curr_lang], T['edu_opts'][curr_lang])
        experience = st.selectbox(T['exp'][curr_lang], T['exp_opts'][curr_lang])
        
        submit_demo = st.form_submit_button(T['start_btn'][curr_lang])
        
        if submit_demo:
            st.session_state['user_info'] = {
                "age": age,
                "gender": gender,
                "education": education,
                "experience": experience,
                "language": curr_lang, # Salviamo anche la lingua scelta
                "session_id": str(datetime.now().timestamp())
            }
            st.session_state['force_scroll'] = True
            st.rerun()

# ==========================================
# FASE 2: VALUTAZIONE
# ==========================================
else:
    # ---------------------------------------------------------
    # 1. LOGICA CAMBIO LINGUA "LIVE"
    # Se l'utente ha cambiato lingua nel selettore, cerchiamo 
    # la versione tradotta dello stesso testo che sta leggendo.
    # ---------------------------------------------------------
    if st.session_state['current_text'] is not None:
        text_obj = st.session_state['current_text']
        target_lang = st.session_state['language_choice']
        
        # Se la lingua del testo attuale è diversa da quella scelta nel menu
        if text_obj.get('lang') != target_lang:
            # Cerchiamo nel dataset un testo con lo STESSO 'prompt' ma nella NUOVA lingua
            # next() prende il primo risultato trovato o restituisce None
            versione_tradotta = next(
                (t for t in data_texts if t['prompt'] == text_obj['prompt'] and t['lang'] == target_lang), 
                None
            )
            
            if versione_tradotta:
                # Sostituiamo il testo in memoria con quello tradotto
                st.session_state['current_text'] = versione_tradotta
                st.rerun() # Ricarichiamo la pagina per mostrare il nuovo testo
            else:
                # Caso raro: traduzione mancante
                st.warning(f"⚠️ Traduzione in {target_lang} non disponibile per questo testo.")

    # ---------------------------------------------------------
    # 2. GESTIONE SCROLL (Codice precedente)
    # ---------------------------------------------------------
    if st.session_state.get('force_scroll', False):
        scroll_to_top()
        st.session_state['force_scroll'] = False

    placeholder_valutazione = st.empty()

    with placeholder_valutazione.container():
        st.title(T['eval_title'][curr_lang])
        
        # LOGICA DI PESCA (FILTRATA PER LINGUA)
        if st.session_state['current_text'] is None:
            # Filtro 1: Non ancora visti
            # Filtro 2: Corrispondono alla lingua scelta (campo 'lang' nel JSON)
            # Nota: useremo .get('lang', 'en') per defaultare a inglese se manca il campo
            testi_disponibili = [
                t for t in data_texts 
                if t['id'] not in st.session_state['seen_ids'] 
                and t.get('lang', 'en').lower() == curr_lang
            ]
            
            if not testi_disponibili:
                st.success(T['finish_msg'][curr_lang])
                st.session_state['finito'] = True
                if st.button("Termina"): # Bottone di fallback
                    st.stop()
                st.stop()
            
            st.session_state['current_text'] = random.choice(testi_disponibili)
        
        texto = st.session_state['current_text']
        
        # Mostra Testo
        label_id = T['text_id_label'][curr_lang]
        label_seen = T['seen_label'][curr_lang]
        st.info(f"📄 **{label_id}: {texto['id']}** ({label_seen}: {len(st.session_state['seen_ids'])})")
        
        st.markdown(f"### {texto['text']}")
        st.markdown("---")
        st.write(T['instructions'][curr_lang])
        
        # Form Valutazione
        with st.form("evaluation"):
            m1 = st.slider(T['q1'][curr_lang], 1, 5, 3)
            m2 = st.slider(T['q2'][curr_lang], 1, 5, 3)
            m3 = st.slider(T['q3'][curr_lang], 1, 5, 3)
            m4 = st.slider(T['q4'][curr_lang], 1, 5, 3)
            m5 = st.slider(T['q5'][curr_lang], 1, 5, 3)
            m6 = st.slider(T['q6'][curr_lang], 1, 5, 3)
            m7 = st.slider(T['q7'][curr_lang], 1, 5, 3)
            m8 = st.slider(T['q8'][curr_lang], 1, 5, 3)
            m9 = st.slider(T['q9'][curr_lang], 1, 5, 3)
            m10 = st.slider(T['q10'][curr_lang], 1, 5, 3)
            m11 = st.slider(T['q11'][curr_lang], 1, 5, 3)
            
            submit_eval = st.form_submit_button(T['submit_btn'][curr_lang])

    # LOGICA POST INVIO
    if submit_eval:
        placeholder_valutazione.empty()
        
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        user = st.session_state['user_info']
        
        # Aggiungiamo user['language'] alla riga da salvare
        row_to_append = [
            timestamp,
            user['session_id'],
            user.get('language', 'it'), # Colonna lingua
            user['gender'],
            user['age'],
            user['education'],
            user['experience'],
            texto['id'],
            texto['author'],
            texto['text'],
            m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11
        ]
        
        successo = False

        try:
            sheet = get_google_sheet()
            sheet.append_row(row_to_append)
            successo = True
        except Exception as e:
            if "200" in str(e):
                successo = True
            else:
                st.error(f"{T['error_save'][curr_lang]}: {e}")

        if successo:
            st.session_state['seen_ids'].append(texto['id'])
            st.success(T['success_msg'][curr_lang])
            
            st.session_state['current_text'] = None
            scroll_to_top()
            time.sleep(1.5)
            st.rerun()

    if not submit_eval:
        st.markdown("---")
        if st.button(T['exit_btn'][curr_lang]):
            st.session_state['finito'] = True
            st.rerun()